services:
  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 2gb
    env_file: ./db.env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db
networks:
  db:
      name: database_network
      driver: bridge
volumes:
  postgres-data: