services:
  neurochecker_front-end:
    image: "devpieter/neuro-checker_frontend:latest"
    container_name: neurochecker_front-end
    restart: unless-stopped
    networks:
      - proxy
    ports:
      "3000:3000"
    env_file:
      - ./neurochecker_front-end.env
networks:
  proxy:
    external: true